DROP TABLE IF EXISTS transfers;
DROP TABLE IF EXISTS entries;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS "Currency";
DROP TYPE IF EXISTS "AccountType";
DROP TYPE IF EXISTS "AccountStatus";
